### ISSUE TITLE
Use esp32 cam modules stream

### ISSUE THREAD

**Issue by mhamidjamil** [mhamidjamil/orangepi#10]
Write a python script which uses esp32 cam module stream, if any changes detected by cam module, script should perform a defined action like sending notification or turning on/off any electrical appliances (this output behavior is dependent on environmental factors, like if user has ture on motoring mode then it should send message, or if user has turn on power saving mode then that script should check if there is any person detected by camera if no then turn off unwanted electrical appliances)

**Comment by wasey-rao** [comment]
Completed in #143
