### ISSUE TITLE
Separate loggers functionality.

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/orangepi#103]

**Comment by wasey-rao** [comment]
I think it would be a better idea to separate exception loggers functionality from flask app, because we need to write exception no matter flask script is running or not, as we need it in script_inspectore.py and we got some permission issue so it would be easy to debug and solve these issues.

**Comment by mhamidjamil** [comment]
I was planing to use python build in [loggers functionality](https://chat.openai.com/share/15c618db-0fc6-43da-95f2-e21ab9564c6c).

**Comment by mhamidjamil** [comment]
logger implemented and in functional state closing this issue
