### ISSUE TITLE
Show CPU temperature on dashboard

### ISSUE THREAD

**Issue by mhamidjamilraza** [mhamidjamil/orangepi#14]
Make your own web page which display useful readings as mentioned in #11 and in addition to that feature also add this new feature:
That dashboard should also show temperature (graph) of orange-pi CPU temperature, as it shown on pi hole project dashboard, here are the required features regarding this _new functionality_:
- [ ] User can scroll through that graph at least 50 or more readings should be there, 10 by default and rest of other should be scrollable.
- [ ] Use Orange pi to display all of these readings (including room temperature/humidity and other readings which are synced with thingspeak)
- [ ] If the temperature of CPU reaches the max temperature, alert user via WhatsApp (if fail then) sim message. #9

**Comment by mhamidjamil** [comment]
Need it urgently as today i installed lot of libraries and packages I noticed my CPU temperature raised up-to 72 which i alarming situation for orange pi.

**Comment by mhamidjamil** [comment]
Today i figure out how to see the CPU temperature,
You can watch CPU temperature by following these steps:

- First go to this directory: `/sys/class/thermal` by typing `cd /sys/class/thermal`
- then to watch live CPU temperature, typing this in terminal: `watch -n 1 cat thermal_zone*/temp`
you'll see temperature like this:
```
Every 1.0s: cat thermal_zone0/temp thermal_zone1/temp thermal_zone2/temp thermal_...  orangepi: Mon Jan 15 04:41:15 2024

33307
33307
33307
33307
33307
33307
33307

```

so let take **33307** it means 33.307 degree, now the strategy is clear i just need to grab these reading after each second and display on serial terminal or also can send message if temperature went to unexpected value.

**Comment by mhamidjamil** [comment]
Today I benchmark my CPU:
```
sysbench --test=cpu --cpu-max-prime=2000 run
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
sysbench 1.0.20 (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Prime numbers limit: 2000

Initializing worker threads...

Threads started!

CPU speed:
    events per second: 23657.57

General statistics:
    total time:                          10.0002s
    total number of events:              236631

Latency (ms):
         min:                                    0.04
         avg:                                    0.04
         max:                                    0.58
         95th percentile:                        0.04
         sum:                                 9961.56

Threads fairness:
    events (avg/stddev):           236631.0000/0.00
    execution time (avg/stddev):   9.9616/0.00
```

**Comment by mhamidjamil** [comment]
CPU stress test:
`stress --cpu 4 --timeout 300s`

**Comment by mhamidjamil** [comment]
closing this as i have setup Grafana and the influx db for this and code updated accordingly.
