### ISSUE TITLE
where are logs or notifications of camera stream usage?

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/orangepi#146]
@mhamidjamil I've noticed that the webcam was accessed briefly, raising concerns about potential unauthorized use. To address this, we should prioritize implementing a notification system that alerts the user whenever any camera is accessed. Additionally, it is essential to move both the `ntfy` and `.env` files to the project scope, ensuring they are managed consistently across the entire project. This will enhance security and provide better control over access to these critical files.

**Comment by mhamidjamil** [comment]
fixed in #145
