### ISSUE TITLE
Need to change loggers location.

### ISSUE THREAD

**Issue by mhamidjamil** [mhamidjamil/orangePi#67]
As we have added logger's functionality, but these are saving logs in the same directory of code so whenever we pull latest code, we need to either stash or checkout, so I have two solutions:

- Change the default location of logger (preferable)
- adds these loggers to git ignore so they won't affect any more.

**Comment by Amenawon** [comment]
Hey! Could you please assign this to me?

**Comment by mhamidjamil** [comment]
@Amenawon Please have a look at this issue #71 and then you need to work on staging branch I recently updated the code, feel free to ask for more details if you need and can you please provide any estimate, or should I take care of this issue? as it's not a big deal for me and we must have to solve #71.

**Comment by mhamidjamil** [comment]
Currently I have solved this issue by granting local user access by:
`chmod +x ngrok_logger.txt`
