### ISSUE TITLE
Please use pylint or other packages for code clarification and beauty.

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/orangePi#80]

**Comment by mhamidjamil** [comment]
ok, I started working on develop branch to improve my code.

**Comment by wasey-rao** [comment]
@mhamidjamil please update pylint rating here after your work.

**Comment by mhamidjamil** [comment]
Sure,
Today's rating improved from 4.** to 6.78 will continue in morning or when i get time. By the way check are now working fine when we push code to develop they auto start.
