### ISSUE TITLE
Improve service functionality

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/orangepi#97]

**Comment by wasey-rao** [comment]
If you type `uptime` in terminal you will get this output:
`03:02:43 up 0 min,  3 users,  load average: 0.85, 0.24, 0.08`
you need to work on this so if the uptime of system is less then 20 mints then you need to add the sleep time of 10 minutes other wise we can skip that delay it will help in testing and improve the work flow.

**Comment by mhamidjamil** [comment]
I have updated delay time, but because of other priorities we are moving next and closing this issue, fell free to open this is you still face any issue.
